version: "3"
services:
 db:
   image: mysql:5.7
   #container_name: "mysql57"
   volumes:
     - ./db/mysql:/var/lib/mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root_admin
     MYSQL_DATABASE: wordpress_db
     MYSQL_USER: wp-user
     MYSQL_PASSWORD: wp-user

 wordpress:
   image: wordpress:latest
   #container_name: "wordpress"
   volumes:
     - ./wordpress/html:/var/www/html
     - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
   restart: always
   depends_on:
     - db
   ports:
     - 80:80
   environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_NAME: wordpress_db
     WORDPRESS_DB_USER: wp-user
     WORDPRESS_DB_PASSWORD: wp-user

 phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   #container_name: "phpmyadmin"
   restart: always
   depends_on:
     - db
   ports:
     - 8888:80
